- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- config/custom-environment-variables.json
- config/default.json
- docker-compose.yml
- src/main/app.ts
https://tools.hmcts.net/jira/browse/ROC-9708
Add dummy property to test flux config
```
[ ] Yes
[X] No
```
> add dummy property to test flux config

- package.json
- yarn.lock
N/A
Upgrade nested dependencies ajv and follow-redirects to fix vulnerabities
```
[ ] Yes
[X] No
```
> Upgrade nested dependencies ajv and follow-redirects

- nodemon.json
https://tools.hmcts.net/jira/browse/CIV-1393
Fixing when try to run nodemon
```
[ ] Yes
[x] No
```
> fix nodemon configuration

- src/main/common/form/validationErrors/errorMessageConstants.ts
- src/test/unit/routes/features/response/citizenPhoneDetails/citizenPhoneController.test.ts
> CIV-1395 fix error message on phone number page

- src/main/common/form/models/citizenTelephoneNumber.ts
- src/main/common/form/validationErrors/errorMessageConstants.ts
- src/main/common/form/validators/optionalIntegerValidator.ts
- src/main/modules/draft-store/index.ts
- src/main/views/features/response/citizenPhoneNumber/citizen-phone.njk
- src/test/unit/routes/features/response/citizenPhoneDetails/citizenPhoneController.test.ts
https://tools.hmcts.net/jira/browse/CIV-1395
```
[ ] Yes
[x ] No
```
> Civ 1395 further changes to error message

- package.json
- src/main/modules/draft-store/index.ts
- src/main/modules/health/index.ts
- webpack/scss.js
- yarn.lock
N/A
Log connection string to troubleshoot invalid password error in demo
```
[ ] Yes
[ ] No
```
> Add connection string log

- src/main/modules/draft-store/index.ts
- src/main/modules/health/index.ts
N/A
Log connection string to troubleshoot invalid password error in demo
```
[ ] Yes
[X] No
```
> Log connection string to troubleshoot invalid password error in demo

- src/main/common/models/civilClaimResponse.ts
- src/main/modules/draft-store/draftStoreService.ts
- src/test/a11y/a11y.ts
- src/test/unit/app/client/civilServiceClient.test.ts
- src/test/unit/modules/draft-store/draftStoreService.test.ts
https://tools.hmcts.net/jira/browse/CIV-1525
```
[ ] Yes
[x ] No
```
> Civ 1525 redis claim service

- src/main/app/client/civilServiceClient.ts
- src/main/common/form/validators/arrayAtLeastOneSelectedValidator.ts
- src/main/modules/draft-store/draftStoreService.ts
- src/main/modules/statementOfMeans/disabilityService.ts
- src/main/modules/statementOfMeans/severeDisabilityService.ts
- src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
- src/test/unit/modules/draft-store/draftStoreService.test.ts
N/A
Fix lint warnings
```
[ ] Yes
[X] No
```
> Fix lint warnings

- package.json
N/A
Remove duplicate dependency declaration
```
[ ] Yes
[X] No
```
> Remove duplicate dependency in package.json

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- config/default.yaml
- src/main/app/client/civilServiceClient.ts
- src/main/modules/properties-volume/index.ts
> Feature 1309 - adding the secret for idam

- src/main/views/webpack/js-template.njk
https://tools.hmcts.net/jira/browse/CIV-1765
Hidden fields are not toggled/shown based on selecting yes or no button.
```
[x] Yes
[ ] No
```
> Fix: bug loading main-dev.js

- package.json
- src/main/modules/draft-store/index.ts
- src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
- src/main/routes/features/response/financialDetails/financialDetailsController.ts
- src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts
- src/test/unit/modules/draft-store/draftStore.test.ts
- src/test/unit/modules/statementOfMeans/dependants/childrenDisabilityService.test.ts
- src/test/unit/routes/features/response/financial-details/financialDetailsController.test.ts
- src/test/unit/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.test.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/CIV-1942
[Fix vulnerability:](https://github.com/hmcts/civil-citizen-ui/commit/5b083b5ced649becd317756d3cd893b49a0e5272) https://github.com/advisories/GHSA-fwr7-v2mv-hh25
```
[ ] Yes
[X] No
```
> Fix vulnerability: https://github.com/advisories/GHSA-fwr7-v2mv-hh25

- jest.config.js
- jest.setup.redis-mock.js
- package.json
- yarn.lock
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
fix pipeline 
```
[ ] Yes
[x] No
```
> fix ioredis-mock

- src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
https://tools.hmcts.net/jira/browse/CIV-2039
```
[ ] Yes
[ x] No
```
> CIV-2039 -fix bug overriding statement of means

- src/main/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.ts
- src/test/unit/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.test.ts
https://tools.hmcts.net/jira/browse/CIV-2114
```
[ ] Yes
[x ] No
```
> CIV-2114 fix the url where the user should go after court orders

- package.json
https://tools.hmcts.net/jira/browse/CIV-1280
Remove transitive dependency as it has been resolved by axios package upgrade
```
[ ] Yes
[x] No
```
> CIV-1280 - TechDebt - remove follow-redirects transitive dependency

- src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
- src/main/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.ts
N/A
Remove major code smells
```
[ ] Yes
[X] No
```
> Remove code smells

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- src/main/modules/properties-volume/index.ts
https://tools.hmcts.net/jira/browse/CIV-1737
Rename Citizen UI IDAM secret key
```
[ ] Yes
[X] No
```
> rename Citizen UI IDAM secret key

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- infrastructure/main.tf
- src/main/modules/properties-volume/index.ts
https://tools.hmcts.net/jira/browse/CIV-2774
Second step to complete renaming of Redis instance subdomain. 1st step completed by this PR: https://github.com/hmcts/civil-citizen-ui/pull/480 
Change subject of current PR is to point CCUI service to the new instance created by this PR https://github.com/hmcts/civil-citizen-ui/pull/480 and to decommission the old Redis instance.
```
[ ] Yes
[X] No
```
> Point CCUI to recently created Redis instance and decommission old one

- src/main/services/features/response/checkAnswersService.ts
- src/test/unit/services/features/response/checkAnswersService.test.ts
- src/test/utils/mockClaimForCheckAnswers.ts
> Hide financial details on check answers if pay immediately is selected

- src/main/app/client/civilServiceClient.ts
- src/main/common/models/feeRange.ts
- src/main/routes/features/response/eligibility/sendYourResponseByEmailController.ts
- src/test/unit/app/client/civilServiceClient.test.ts
- src/test/utils/mocks/feeRangesMock.json
https://tools.hmcts.net/jira/browse/CIV-3042
some additional changes to cope with unexpected data that is returned by the fees api
```
[ ] Yes
[ x] No
```
> Civ 3042 fix translation with unexpected data

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
- src/main/views/features/response/statementOfMeans/otherDependants/other-dependants.njk
https://tools.hmcts.net/jira/browse/CIV-3173
text messages are missing
```
[ ] Yes
[x] No
```
> fix translation

- charts/civil-citizen-ui/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-3120
```
[ ] Yes
[ ] No
```
> CIV-3120 add constant to point to claim store for civil_serfice image

- charts/civil-citizen-ui/values.preview.template.yaml
n/a
Add variable for judicial reference data.
This should fix deployment issues
```
[ ] Yes
[x] No
```
> build(fix): add config for judicial ref data

- src/main/routes/urls.ts
> Fix: delete duplicate url

- Jenkinsfile_CNP
- bin/add-roles.sh
> Fix the PRs

- src/main/views/features/mediation/mediation-disagreement.njk
- src/test/unit/views/features/mediation/i-dont-want-free-mediation.test.ts
- src/test/unit/views/features/mediation/mediation-disagreement.test.ts
https://tools.hmcts.net/jira/browse/CIV-2607
Add view unit tests for `mediation disagreement` and `I dont want free mediation` pages
```
[ ] Yes
[x] No
```
> Tech debt - CIV-2607 Missing Mediation View Unit Tests

- charts/civil-citizen-ui/values.preview.template.yaml
- src/main/app/client/civilServiceClient.ts
- src/main/app/client/civilServiceUrls.ts
- src/main/common/models/events/caseEvent.ts
- src/main/common/models/events/eventDto.ts
- src/main/routes/features/response/checkAnswersController.ts
- src/test/unit/app/client/civilServiceClient.test.ts
https://tools.hmcts.net/jira/browse/CIV-2824
```
[ ] Yes
[x ] No
```
> Civ 2824 client to submit event

- src/main/common/form/models/numberOfDays.ts
- src/main/common/models/claim.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/response/responseType/citizenResponseTypeController.ts
https://tools.hmcts.net/jira/browse/CIV-3453
Remove numberOfDays enum and responseInDays function as it is not applicable anymore since all claims have 28 days response deadline
```
[ ] Yes
[x] No
```
> TechDebt - CIV-3453 - Remove NumberOfDays

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-3376
```
[ ] Yes
[ ] No
```
> Civ 3376 enable elastic search in preview

- bin/add-roles.sh
- src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
adding new access-profile GS_profile into add-roles.sh
```
[ ] Yes
[x ] No
```
> adding new access-profile GS_profile into add-roles.sh

- charts/civil-citizen-ui/values.preview.template.yaml
n/a
As per Sampan's comment - https://github.com/hmcts/ccd-data-store-api/pull/2063/files
```
[ ] Yes
[x] No
```
> Fix - add nameOverride for elasticsearch

- src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
- src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
- src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
n/a
Move dates further in the future to avoid test failures.
To be properly addressed with CIV-3856 tech debt ticket
https://tools.hmcts.net/jira/browse/CIV-3856
```
[ ] Yes
[x] No, until next year
```
> fix - move dates to the future

- src/main/common/form/models/statementOfMeans/partner/cohabiting.ts
- src/main/common/form/models/statementOfMeans/partner/partnerAge.ts
- src/main/common/form/models/statementOfMeans/partner/partnerDisability.ts
- src/main/common/form/models/statementOfMeans/partner/partnerSevereDisability.ts
- src/main/modules/i18n/locales/cy.json
- src/main/views/features/response/statementOfMeans/partner/partner-age.njk
- src/main/views/features/response/statementOfMeans/partner/partner-disability.njk
- src/main/views/features/response/statementOfMeans/partner/partner-severe-disability.njk
- src/main/views/features/response/statementOfMeans/partner/partner.njk
https://tools.hmcts.net/jira/browse/CIV-3454
Re-creating PR #654 
```
[ ] Yes
[x] No
```
> CIV-3454 - Re-create PR

- src/main/common/form/models/claimSummarySection.ts
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/dashboard/claimSummaryController.ts
- src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionOne.ts
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionTwo.ts
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
- src/main/services/features/dashboard/claimSummary/latestUpdateService.ts
- src/main/views/features/dashboard/claim-summary-content.njk
- src/main/views/features/dashboard/claim-summary.njk
- src/main/views/features/dashboard/item-content.njk
- src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
- src/test/unit/services/features/dashboard/claimSummary/latestUpdateService.test.ts
https://tools.hmcts.net/jira/browse/CIV-2558
remove lang and translation structure from service and controller
```
[ ] Yes
[x] No
```
> remove lang from service and controller

- src/main/modules/draft-store/redisData.json
Update redisData with cases to test deadline paths
> Update: redisData

- src/main/routes/features/dashboard/claimSummaryController.ts
https://tools.hmcts.net/jira/browse/CIV-4222
Error Claim Summary page
```
[ ] Yes
[x] No
```
> CIV-4222 - Fix: add next claim summary

- Jenkinsfile_CNP
- bin/variables/load-preview-environment-variables.sh
- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
> change to https services related to ccd and civil service

- src/main/assets/js/calculate-length-repayment.js
https://tools.hmcts.net/jira/browse/CIV-4440
Fixes issue where both Welsh and English languages are displayed on the header.
```
[ ] Yes
[x] No
```
> CIV-4440 - Bugfix - Elivs operator on schedule container children

- src/main/services/features/response/statementOfMeans/otherDependants/otherDependantsService.ts
- src/test/unit/services/features/response/statementOfMeans/otherDependants/otherDependants.test.ts
https://tools.hmcts.net/jira/browse/CIV-3935
Clear number of people and details when selection is no
```
[ ] Yes
[x] No
```
> CIV-3935 - Fix - Clear Data On Selection Change

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/public/eligibility/not-eligible-includes/claim-for-tenancy-deposit.njk
- src/main/views/features/public/eligibility/not-eligible.njk
- src/test/unit/views/features/public/eligibility/not-eligible.test.ts
https://tools.hmcts.net/jira/browse/CIV-3741
You can’t make a claim for a tenancy deposit using this service
```
[ ] Yes
[x] No
```
> re-feature/CIV-3741/not eligible for tenancy deposit

- src/main/modules/draft-store/redisData.json
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/public/firstContact/claimSummaryController.ts
- src/main/routes/routes.ts
- src/main/routes/urls.ts
- src/main/views/features/public/firstContact/claim-summary.njk
- src/main/views/macro/evidence-summary.njk
- src/main/views/macro/timeline-summary.njk
- src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
- src/test/unit/views/features/public/firstContact/claim-summary.test.ts
- src/test/utils/mockDraftStore.ts
- src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
https://tools.hmcts.net/jira/browse/CIV-262
- Implement first contact - claim summary page driven by the cookie options (set to be developed with CIV-260 and 261)
- update mock claim to include timeline and evidence records
```
[ ] Yes
[x] No
```
> CIV-262 - Feature - Claim Details Summary

- src/test/unit/views/features/claim/resolving-this-dispute.test.ts
> Hotfix - Refactor test to work with cookie banner

- src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
- src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
- src/test/utils/dateUtils.ts
https://tools.hmcts.net/jira/browse/CIV-3856
- created a function to get the next year values for future dates in tests 
```
[ ] Yes
[x] No
```
> tech-debts/CIV-3856-test-with-dynamic-dates

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-4810
Change respond days from 19 to 28.
```
[ ] Yes
[x] No
```
> CIV-4810 - TechDebt - Change respond days to 28

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.yaml
changing the service url to http
changing the service url to http
```
[ ] Yes
[x ] No
```
> changing the service url to http

- charts/civil-citizen-ui/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-4974
```
[ ] Yes
[ ] No
```
> CIV-4974 - add robotics recipient for spec secret

- bin/add-roles.sh
Add new roles to add-roles.sh file to fix Jenkins pipeline invalid profile access issue.
```
[ ] Yes
[x] No
```
> Update: add new roles

- Jenkinsfile_CNP
fix ccd definition import
```
[ ] Yes
[ ] No
```
> fix ccd definition import on preview

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.yaml
Remove cmc-s2s-secret secret
```
[ ] Yes
[ x ] No
```
> Remove cmc-s2s-secret secret

- .github/workflows/stale.yml
added bot to close stale PRs
```
[ ] Yes
[x ] No
```
> adding a bot to close stale PRs

- .github/workflows/stale-branches.yml
n/a
As per conversation with Akriti we are creating stale branches action 
```
[ ] Yes
[x] No
```
> Stale Branches: Action to delete stale branches

- package.json
- yarn.lock
Add minimatch version 3.0.5 to resolutions
```
[ ] Yes
[x] No
```
> New: add minimatch to resolutions

- src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
- src/main/services/features/claim/yourDetails/claimantDetailsService.ts
- src/main/views/features/claim/yourDetails/claimant-individual-details.njk
https://tools.hmcts.net/jira/browse/CIV-5455
- update logic to save individual and sole trader details
**Note:**
This ticket unblocks CIV-5289
```
[ ] Yes
[x] No
```
> CIV-5455 - Bug Fix - Save individual and sole trader details

- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-5190
Removed whitespace from time
```
[ ] Yes
[ ] No
```
> CIV-5021 remove whitespace from time

- src/main/common/models/directionsQuestionnaire/hearing/determinationWithoutHearing.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/directionsQuestionnaire/experts/defendant-expert-evidence.njk
- src/main/views/features/directionsQuestionnaire/hearing/determination-without-hearing.njk
https://tools.hmcts.net/jira/browse/CIV-5252
Screens:
DQ-Small Claims-Determination without Hearing Questions
DQ-FT-Do you want to use expert evidence
DQ-Small Claims-Using an expert
```
[ ] Yes
[X] No
```
> CIV-5252: Welsh Translations 18

- src/main/common/models/claim.ts
- src/main/routes/features/response/submitConfirmationController.ts
- src/main/routes/guards/responseSubmitDateGuard.ts
- src/main/routes/routes.ts
- src/test/unit/routes/features/response/submitComfirmationController.test.ts
- src/test/unit/routes/guards/responseSubmitDateGuard.ts
https://tools.hmcts.net/jira/browse/CIV-4772
Implement response submit guard
```
[ ] Yes
[x] No
```
> CIV-4772 - Tech Debt - Response Submit Guard

- src/main/modules/i18n/locales/cy.json
> CIV-4832 - translation added

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/response/ageEligibility/under-18.njk
https://tools.hmcts.net/jira/browse/CIV-5036
add missing translation for under-18
```
[ ] Yes
[x] No
```
> CIV-5036 - fix translation for under 18 page

- src/main/modules/i18n/locales/cy.json
- src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
- src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
- src/main/views/features/directionsQuestionnaire/support-required-list.njk
https://tools.hmcts.net/jira/browse/CIV-5255
The scope of this ticket is to develop Welsh content translation of the following screens: 
DQ-Do you want an extra 4 weeks to settle the claim
DQ-Enter the expert's details
```
[ ] Yes
[ ] No
```
> CIV-5255 - CUI Welsh UI Translations 21

- charts/civil-citizen-ui/values.preview.template.yaml
- src/main/modules/i18n/locales/cy.json
- src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
- src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
Reverting back master push 
```
[ ] Yes
[ ] No
```
> Reverting back master push

- Jenkinsfile_CNP
- bin/variables/load-staging-environment-variables.sh
- charts/civil-citizen-ui/values.aat.template.yaml
> update staging environment variables

- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
CIV-6106
Removed user-profile-importer
Changed user-profile API to use AAT instance.
Increase ccd-data-store cpu
Disable camunda cron 
```
[ ] Yes
[ x ] No
```
> CIV-6106 - Remove the dependency on User Profile

- src/main/modules/draft-store/draftStoreService.ts
- src/main/routes/features/response/checkAnswersController.ts
- src/test/unit/modules/draft-store/draftStoreService.test.ts
https://tools.hmcts.net/jira/browse/CIV-5706
added a code changes to remove claim from redis once response has been submitted.
```
[ ] Yes
[x] No
```
> CIV_5706 : Remove claim from redis once response has been submitted.

- src/main/routes/features/directionsQuestionnaire/experts/expertDetailsController.ts
- src/main/routes/features/directionsQuestionnaire/experts/permissionForExpertController.ts
- src/main/routes/features/directionsQuestionnaire/hearing/determinationWithoutHearingController.ts
- src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
- src/test/unit/common/utils/dateUtils.test.ts
- src/test/unit/routes/features/directionsQuestionnaire/experts/expertDetailsController.test.ts
- src/test/unit/routes/features/directionsQuestionnaire/experts/permissionForExpertController.test.ts
- src/test/unit/routes/features/directionsQuestionnaire/hearing/determinationWithoutHearingController.test.ts
- src/test/unit/routes/features/directionsQuestionnaire/supportRequiredController.test.ts
https://tools.hmcts.net/jira/browse/CIV-6002
DQ Navigation fix
```
[ ] Yes
[x] No
```
> Civ 6002 dq navigation fix

- charts/civil-citizen-ui/values.preview.template.yaml
adding ccd field limit
```
[ ] Yes
[x ] No
```
> adding ccd field limit

- jest.config.js
> ignoring some tests for pipeline to work

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- jest.config.js
CIV-5967
Remove Bitnami Dependency for postgres
```
[ ] Yes
[ x ] No
```
> CIV-5967 - Remove Bitnami Dependency

- src/test/functionalTests/features/response/pages/checkYourAnswers.js
> added code to exclude the submission in AAT environment

- src/main/modules/i18n/locales/cy.json
> Translation missing added

- Jenkinsfile_CNP
- package.json
N/A
fix preview environment to include cui events and fields
```
[ ] Yes
[ ] No
```
> enable cui import ccd definitions

- charts/civil-citizen-ui/Chart.yaml
Update chart dependencies
https://github.com/hmcts/civil-citizen-ui/pull/1281/files
https://github.com/hmcts/civil-citizen-ui/pull/1285/files
```
[ ] Yes
[x] No
```
> Update: update chart dependencies

- Jenkinsfile_CNP
- src/main/app/client/civilServiceClient.ts
Fix: delete ccd test branch and logs
```
[ ] Yes
[x] No
```
> Fix: delete ccd test branch and log

- .github/CODEOWNERS
- .github/workflows/main.yml
CIV-5433
Add PR Title validation and Code Owners
```
[ ] Yes
[ x ] No
```
> CIV-5433 - Add PR Title validation and Code Owners

- Jenkinsfile_CNP
- package.json
> CIV-6992 updated JenkinsCNP._Snyk

- infrastructure/variables.tf
> CIV-0000 Remove ilbip terraform var as it's no longer used

- charts/civil-citizen-ui/values.preview.template.yaml
- src/main/common/utils/taskList/tasks/taskListHelpers.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/mediation/iDontWantFreeMediationController.ts
- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
- src/main/views/features/mediation/i-dont-want-free-mediation.njk
- src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
- src/test/unit/routes/features/mediation/iDontWantFreeMediationController.test.ts
- src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
- src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.test.ts
https://tools.hmcts.net/jira/browse/CIV-6177
Claimant Intend: Response Task List - Part Admit + Pay immediately (Options: Accept and reject £xx, Free telephone mediation)
```
[ ] Yes
[x] No
```
> CIV-6177 claimant response task list PA PI._Snyk

- src/test/unit/common/models/directionQuestionnaire/directionQuestionnaire.test.ts
- src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
- src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
- src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
- src/test/unit/services/features/directionsQuestionnaire/otherWitnessesService.test.ts
> CIV-0000 Fix build errors

- charts/civil-citizen-ui/Chart.yaml
upgrade node version 
```
[ ] Yes
[x] No
```
> CIV-0000 fix_node_version

- infrastructure/key-vault.tf
CIV-5698
Do not create Managed Identity in Terraform
```
[ ] Yes
[ x ] No
```
> CIV-5698 - Do not create MI in TF

- infrastructure/key-vault-secrets-civil.tf
CIV-5698
Temp add back in secret
```
[ ] Yes
[ x ] No
```
> CIV-5698 - Temp add back in secret

- src/main/common/models/claimantResponse/ccj/ccjRequest.ts
- src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
hot fix for build errors
fix build errors.
```
[ ] Yes
[x] No
```
> CIV-0000 fix build error._Snyk

- infrastructure/key-vault.tf
CIV-5698
Grant Civil MI access to Vault
```
[ ] Yes
[ x ] No
```
> CIV-5698 - Grant Civil MI access to Vault

- package.json
Added  start:redis to facilitate run redis locally 
```
[ ] Yes
[x] No
```
> CIV-0000 added start:redis on package.json

- bin/add-roles.sh
Adding new Access Profiles
```
[ ] Yes
[x ] No
```
> CIV-0000 - Adding new Access Profiles

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
Upgrading elastic search version
```
[ ] Yes
[x ] No
```
> CIV-0000 - Upgrading elastic search version

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
N/A
Bumping Service Charts in line with changes made in: 
- https://github.com/hmcts/civil-service/pull/2331
- https://github.com/hmcts/civil-service/pull/2402
```
[ ] Yes
[x] No
```
> CIV-0000 - update: civil-service charts and env var

- Jenkinsfile_CNP
- bin/variables/load-staging-environment-variables.sh
> CIV-0000 Attempt to fix aat urls

- charts/civil-citizen-ui/values.preview.template.yaml
- src/test/functionalTests/specClaimHelpers/api/apiRequest.js
- src/test/functionalTests/specClaimHelpers/api/steps.js
- src/test/functionalTests/specClaimHelpers/api/testingSupport.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
Added `SERVICE_REQUEST_UPDATE` and `SERVICE_REQUEST_UPDATE_CLAIM_ISSUED` to values.preview. Not added to values.yaml as civil service is not enabled
```
[ ] Yes
[x] No
```
> CIV-0000 Added values to values.preview only for civil service

- src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
Fixed pipeline
```
[ ] Yes
[X] No
```
> CIV-0000 fixed date issue on unit test

- src/main/common/models/summaryList/summaryList.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/dashboard/dashboard.njk
https://tools.hmcts.net/jira/browse/CIV-7438
https://tools.hmcts.net/jira/browse/CIV-7438
```
[ ] Yes
[x] No
```
> CIV-7438 link purpose

- Jenkinsfile_CNP
This PR is used to fix duplication error in CUI side
```
[ ] Yes
[x] No
```
> CIV-0000 Exclude hnl nonprod

- src/main/assets/js/append-row.js
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/mediation/can-we-use.njk
- src/main/views/features/response/statementOfMeans/debts/debts.njk
- src/main/views/macro/bank-account.njk
- src/main/views/macro/employer.njk
- src/main/views/macro/telephone.njk
https://tools.hmcts.net/jira/browse/CIV-7417
- Added missing labels for Form controls
- Fixed form controls have more than one associated labels
```
[ ] Yes
[x] No
```
> CIV-7417 Labels for multi-row

- bin/utils/process-definition.sh
N/A
Point to working version of definition-processor
```
[ ] Yes
[ x] No
```
> CIV-0000 Use working version of definition-processor until it's fixed

- src/test/unit/routes/guards/allResponseTasksCompleteGuard.test.ts
- src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
- src/test/utils/mockClaim.ts
NA
Fixed build errors.
```
[ ] Yes
[x] No
```
> CIV-0000 - Fixed build errors in CUI.

- bin/utils/process-definition.sh
N/A
Revert back to using latest version of definition_processor
```
[ ] Yes
[x] No
```
> CIV-0000 Move back to using the latest definition-processor

- src/main/routes/features/claim/interest/claimInterestController.ts
- src/main/routes/features/claim/interest/claimantInterestFromController.ts
- src/main/routes/features/claim/yourDetails/defendantEmailController.ts
- src/main/routes/features/response/evidence/evidenceController.ts
> CIV-0000 Fix sonar errors

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
NA
added few missing config changes to support WA.
```
[ ] Yes
[x] No
```
> CIV-0000 - Config changes to support WA.

- src/main/common/utils/dateUtils.ts
- src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
- src/test/unit/common/utils/dateUtils.test.ts
- src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
https://tools.hmcts.net/jira/browse/CIV-8391
Save date + 5 days when FullAdmit and Pay Immediately
```
[ ] Yes
[x] No
```
> CIV-8391 add days to paymentDay immediately

- Jenkinsfile_CNP
- charts/civil-citizen-ui/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-7357
testing
```
[ ] Yes
[ ] No
```
> CIV-0000 fix preview environment - enable more memory for ccd data store api

- src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/document/documentDownloadController.ts
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
- src/main/services/translation/convertToCUI/cuiTranslation.ts
- src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
- src/test/unit/routes/features/document/documentDownloadController.test.ts
- src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
https://tools.hmcts.net/jira/browse/CIV-7161
CUI changes to update latest section with SDO order.
<oldPR: https://github.com/hmcts/civil-citizen-ui/pull/1488>
```
[ ] Yes
[x] No
```
> CIV-7498 SDO Latest Update for LIP Defendant.<New PR>

- Jenkinsfile_CNP
> CIV-TASK Fix camunda import

- Jenkinsfile_CNP
- src/main/common/models/ccdResponse/ccdResponse.ts
- src/main/common/models/civilClaimResponse.ts
- src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
- src/main/services/translation/response/ccdTranslation.ts
- src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
- src/test/unit/services/translation/response/ccdTranslation.test.ts
https://tools.hmcts.net/jira/browse/CIV-7139
This PR contains changes for FT related translation
```
[ ] Yes
[x] No
```
> CIV-7139 Clone-Fixed the translation

- src/main/views/features/caseProgression/upload-documents.njk
https://tools.hmcts.net/jira/browse/CIV-7905
Add another and Remove section
```
[ ] Yes
[x] No
```
> CIV-7905 upload model

- src/main/services/translation/response/convertToCCDHearingSupport.ts
https://tools.hmcts.net/jira/browse/CIV-8598
```
[ ] Yes
[x] No
```
> CIV-8598 Bug Fixed for translation

- src/main/views/features/caseProgression/typeOfDocuments.njk
https://tools.hmcts.net/jira/browse/CIV-8554
```
[ ] Yes
[x] No
```
> CIV-8554 cancel text size smaller

- Jenkinsfile_CNP
> CIV-0000 Update Jenkins to Exclude import in AAT

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-8796
```
[ ] Yes
[x ] No
```
> CIV-8796 English and welsh correction

- src/main/modules/draft-store/redisData.json
- src/test/a11y/constants.ts
> CIV-8946 Accessibility urls added for CUI-CP

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/services/features/response/admission/partialAdmission/partialAdmissionService.ts
https://tools.hmcts.net/jira/browse/CIV-7582
This PR has bug fix for Respond to claim section in CYA page 
```
[ ] Yes
[x] No
```
> CIV-7582 - Part Admit and State Paid: Financial details in CYA

- package.json
- yarn.lock
None
Fix security error in master pipeline
```
[ ] Yes
[x] No
```
> CIV-0000 Fix: resolution semver

- src/test/config.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/courtLocation.js
> CIV-0000 FTFix

- Jenkinsfile_CNP
Notify on tech team channel
```
[ ] Yes
[x ] No
```
> CIV-0000 Notify on tech team channel

- Jenkinsfile_CNP
- package.json
- yarn.lock
Temporarily disabling accessibility tests on preview
```
[ ] Yes
[ x] No
```
> CIV-0000 Temporarily disabling accessibility tests on preview

- jest.config.js
- package.json
CIV-0000 fix memory issues
```
[ ] Yes
[ x] No
```
> CIV-0000 fix memory issues

- src/test/functionalTests/tests/response_deadlineExtension_tests.js
> CIV-9218 enable extended response time test

- package.json
- yarn.lock
None
Security check fix
```
[ ] Yes
[x] No
```
> CIV-0000 Update: add minimist and toough-cookie in resolutions

- src/test/functionalTests/tests/response_deadlineExtension_tests.js
Reverts hmcts/civil-citizen-ui#1832
> CIV-9218 revert

- charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
This is the Pr for adding the elastic search size in preview
```
[ ] Yes
[x] No
```
> CIV-0000 Adding Elastic Search Limit

- src/test/config.js
- src/test/functionalTests/specClaimHelpers/api/steps.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecFastTrackLrvLR.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecLRvLR.js
- src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
- src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
- src/test/functionalTests/tests/response_admitAll_tests.js
- src/test/functionalTests/tests/response_deadlineExtension_tests.js
- src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
- src/test/functionalTests/tests/response_partAdmit_tests.js
- src/test/functionalTests/tests/response_rejectAll_tests.js
> CIV-0000 FTFixForMaster

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.yaml
Adding memory to node js pod
```
[ ] Yes
[x ] No
```
> CIV-0000 Adding memory to node js pod

- .github/renovate.json
Update renovate json
```
[ ] Yes
[x ] No
```
> CIV-0000 Update renovate json

- yarn.lock
#1999 #1998 #1974 
```
[ ] Yes
[X] No
```
> CIV-0000 Update dependencies

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.enableWA.preview.template.yaml
CIV-0000 fix wa issue
```
[ ] Yes
[ ] No
```
> CIV-0000 fix wa issue

- charts/civil-citizen-ui/Chart.yaml
- src/test/a11y/a11y.ts
None
Fix accessibility issues
```
[ ] Yes
[ ] No
```
> CIV-000 Ignore accessibility test principle

- src/test/a11y/a11y.ts
Reverts hmcts/civil-citizen-ui#2047
> CIV-0000 Ignore accessibility test principle

- src/main/common/form/models/claimDetails.ts
- src/main/common/models/claim.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
- src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
https://tools.hmcts.net/jira/browse/CIV-10135
Added a latest updated content for  respondent response when its FD + Dispute the claim + with/without mediation.
```
[ ] Yes
[x] No
```
> CIV-1135 - CUI - Defendant LatestUpdate does not have any content for RejectAll and DisputeAll

- .github/workflows/main.yml
Update main.yml to allow 5 digits
```
[ ] Yes
[X] No
```
> CIV-0000 Update main.yml to allow 5 digits

- src/main/app/client/civilServiceClient.ts
- src/test/unit/app/client/civilServiceClient.test.ts
fix quality gate in master
```
[ ] Yes
[x] No
```
> CIV-0000 fix quality gate in master

- Jenkinsfile_CNP
> CIV-0000 remove enable relase helm

- yarn.lock
https://tools.hmcts.net/jira/browse/CIV-8382
```
[ ] Yes
[X] No
```
> CIV-8382  Update dependencies

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-10811
```
[ ] Yes
[x] No
```
> CIV-10811 - fix bundles text

- src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
- src/test/functionalTests/tests/response_negativeScenarios_tests.js
> CIV-0000 fixMaster

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.yaml
resources bump + autoscaling
```
[ ] Yes
[ ] No
```
> CIV-0000 increase memory for nodejs The Second

- src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
- src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
https://tools.hmcts.net/jira/browse/CIV-10950
```
[ ] Yes
[x] No
```
> CIV-10950 - fix latestUpdate hasRespondent1NotAgreedMediation

- infrastructure/_variables.tf
- infrastructure/key-vault.tf
- infrastructure/prod.tfvars
- infrastructure/redis.tf
> CIV-0000 change redis sku from premium to basic in non-prod envs

- src/main/common/models/claimantResponse/ccdClaimantResponse.ts
- src/main/common/models/events/eventDto.ts
- src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
- src/main/services/translation/convertToCUI/cuiTranslation.ts
- src/main/services/translation/response/convertToCCDPaymentOption.ts
- src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
https://tools.hmcts.net/jira/browse/CIV-11068
CCD Translation - Part/Full + Set by date+ Instalments
```
[ ] Yes
[x] No
```
> CIV-11068 - CCD translation

- infrastructure/aat.tfvars
- infrastructure/ithc.tfvars
> CIV-100 Change redis sku in aat/ithc envs

- src/main/routes/guards/claimIssueTaskListGuard.ts
Avoid the claim issue guard on the pay claim fee screen.
```
[ ] Yes
[X] No
```
> CIV-0000  Avoid the claim issue guard on the pay claim fee screen.

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-11129
Misspelled word corrected in Trial Arrangeent Finalise Case Progression heading on the Is your Case Ready for Trial arrangements screen.
```
[ ] Yes
[x] No
```
> CIV-11129 Misspelled word corrected.

- src/test/config.js
> CIV-0000 Update username

- src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
- src/test/functionalTests/specClaimHelpers/fixtures/events/createAnAssistedOrder.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createSDO.js
> CIV-0000 Fix Functional Attempt

- src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/addYourTimeLine.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
>  CIV-0000  Ft fix

- src/test/functionalTests/tests/response_deadlineExtension_tests.js
> CIV-0000 skipping test

- src/test/functionalTests/features/caseProgression/pages/documents.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/evidenceUpload.js
Pr to amend the document upload FTs, it adds the new field introduced by xui 'witnessOptionUploadDate' to the 'documentWitnessSummary' document.
```
[ ] Yes
[x] No
```
> CIV-TASK PR to fix the document upload FTs

- src/main/modules/helmet/index.ts
- src/main/routes/features/public/firstContact/pinController.ts
> CIV-0000 Fix OCMC Pin

- Jenkinsfile_CNP
> locked a11y flaky tests

- src/main/routes/features/claim/yourDetails/claimantDoBController.ts
- src/main/services/translation/response/convertToCCDParty.ts
- src/test/unit/routes/features/claim/claimantDoBController.test.ts
- src/test/unit/services/translation/response/convertToCCDParty.test.ts
https://tools.hmcts.net/jira/browse/CIV-11805
```
[ ] Yes
[x] No
```
> CIV-11895 for merge

- package.json
- src/main/app/client/civilServiceClient.ts
Reverts hmcts/civil-citizen-ui#2722
> CIV-0000 Revert "CIV-0000 Empty PR"

- charts/civil-citizen-ui/Chart.yaml
- src/main/app/client/civilServiceClient.ts
- src/main/app/client/civilServiceUrls.ts
- src/main/common/models/feePayment/paymentInformation.ts
- src/main/routes/features/caseProgression/hearingFee/paymentConfirmationController.ts
- src/main/routes/routes.ts
- src/main/routes/urls.ts
- src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
- src/main/services/features/feePayment/feePaymentService.ts
- src/test/unit/app/client/civilServiceClient.test.ts
- src/test/unit/routes/features/caseProgression/hearingFee/paymentConfirmationController.test.ts
- src/test/unit/services/features/caseProgression/hearingFee/paymentConfirmationService.test.ts
- src/test/unit/services/features/feePayment/feePaymentService.test.ts
- src/test/utils/mocks/civilClaimResponseMock.json
https://tools.hmcts.net/jira/browse/CIV-11489
create new route which the Payment API will use to redirect after payment success/failure
```
[ ] Yes
[x] No
```
> CIV-11489 Pay-Hearing-Fee-Handle-Return-Url

- src/main/common/models/claim.ts
- src/test/unit/services/translation/response/ccdTranslation.test.ts
https://tools.hmcts.net/jira/browse/CIV-11874
Fixing the issue for defendant response document
```
[ ] Yes
[x] No
```
> CIV-11874 Defendant response document

- src/main/routes/features/claimantResponse/courtProposedDateController.ts
https://tools.hmcts.net/jira/browse/CIV-11749
Error message [object Object]
```
[ ] Yes
[x] No
```
> CIV-11749 fix object error

- src/main/common/models/dashboard/dashboardItem.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
- src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
Reverts hmcts/civil-citizen-ui#2544
> CIV-8903 dashboard settlement agreement-revert

- src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/addYourTimeLine.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
> CIV-0000 FixFTs

- src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
https://tools.hmcts.net/jira/browse/CIV-12106
Skipping Assisted Orders tests until issue is fixed
```
[ ] Yes
[X] No
```
> CIV-TASK skipping orders FTs

- charts/civil-citizen-ui/values.preview.template.yaml
> CIV-0000 change api gateway image to old one as latest is not working

- infrastructure/key-vault-secrets-civil.tf
> CIV-0000 Add new keys in the TF

- src/main/app/client/civilServiceClient.ts
- src/test/functionalTests/specClaimHelpers/api/apiRequest.js
> CIV-12104 removed logs

- src/test/functionalTests/specClaimHelpers/api/steps.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
- src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
- src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
- src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
- src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
- src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
https://tools.hmcts.net/jira/browse/CIV-12205
Fixing failing small claims cp tests, dynamically passing the value for responseClaimTrack depending on the claim type.
```
[ ] Yes
[X] No
```
> CIV-12205 - Fixing functional tests

- src/test/functionalTests/specClaimHelpers/api/steps.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
- src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
- src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
- src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
- src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
- src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
- src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
- src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
Fixing failing trial arrangements cp tests, dynamically passing the value for claimsTrack during SDO depending on the claim type.
```
[ ] Yes
[X] No
```
> CIV-TASK fixing trial arrangements FTS

- charts/civil-citizen-ui/Chart.yaml
- src/test/unit/app/client/civilServiceClient.test.ts
- src/test/unit/routes/guards/checkYourAnswersGuard.test.ts
https://tools.hmcts.net/jira/browse/CIV-5453
```
[ ] Yes
[x] No
```
> CIV-5453 Session user id test

- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
https://tools.hmcts.net/jira/browse/CIV-12323
```
[ ] Yes
[X] No
```
> CIV-12323 Fix part admit pay immediately tasklist

- src/main/app.ts
- src/main/modules/oidc/index.ts
- src/main/views/claim-details-tpl.njk
> CIV-0000 redirection to ocmc eligibility

- Jenkinsfile_CNP
> CIV-0000 Update Jenkinsfile_CNP

- package.json
- src/main/app.ts
- yarn.lock
> CIV-12804 adding express-async-error to handle async errors

- src/main/modules/utilityService.ts
- src/main/routes/features/dashboard/claimSummaryController.ts
- src/main/routes/features/dashboard/claimantDashboardController.ts
- src/main/services/dashboard/dashboardInterpolationService.ts
- src/main/services/dashboard/dashboardService.ts
- src/test/unit/modules/utilityService.test.ts
- src/test/unit/services/features/caseProgression/dashboardService.test.ts
- src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Dashboard mapper for urls and other values calculated on front end.
```
[ ] Yes
[x] No
```
> CIV-TASK - dashboard value mapper

- Jenkinsfile_CNP
- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
- src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/repaymentPlan.js
- src/test/unit/common/utils/ageEligibilityVerification.test.ts
- src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
- src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
- src/test/utils/dateUtils.ts
> CIV-0000 remove ga spec

- src/main/modules/nunjucks/index.ts
- src/main/views/claim-details-tpl.njk
[CIV-11605](https://tools.hmcts.net/jira/browse/CIV-11605)
TRACK NON-JAVASCRIPT VISITS IN GOOGLE ANALYTICS
```
[ ] Yes
[x] No
```
> CIV-11605 TRACK NON-JAVASCRIPT VISITS IN GOOGLE ANALYTICS

- src/main/modules/claimDetailsService.ts
- src/main/services/dashboard/dashboardInterpolationService.ts
- src/test/unit/modules/claimDetailsService.test.ts
- src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
https://tools.hmcts.net/jira/browse/CIV-12813
Dashboard notification Full admit, Pay immediately - CCJ link
```
[ ] Yes
[x] No
```
> CIV-12813 Dashboard notification Full admit, Pay immediately - CCJ link

- package.json
- src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
- yarn.lock
> CIV-0000 Fix security issue

- bin/pull-latest-release-asset.sh
- bin/utils/idam-lease-user-token.sh
Fix jq issue
```
[ ] Yes
[ ] No
```
> CIV-00000 Fix jq issue

- src/test/functionalTests/codecept.conf.js
- src/test/functionalTests/tests/wa/welshResponse_caseworker_request_translation_tests.js
> fix flaky functional tests

- src/test/functionalTests/codecept.conf.js
- src/test/functionalTests/commonFeatures/home/pages/login.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecFastTrack.js
- src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
- src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
> CIV-0000 fix login test

- src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
> CIV-0000 hearing date

- src/main/modules/i18n/locales/cy.json
- src/main/routes/features/claim/claimTaskListController.ts
- src/main/services/features/claim/taskListService.ts
https://tools.hmcts.net/jira/browse/CIV-12912
CUI R2 - Welsh translation issue on Claimant Task list page
```
[ ] Yes
[x] No
```
> CIV-12912 fix task list translations

- src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
fix the date on unit test
```
[ ] Yes
[ ] No
```
> CIV-0000 fix date issue

- src/main/common/form/models/claim/claimant/citizenDate.ts
- src/main/common/form/models/claim/claimant/dobDate.ts
- src/main/common/utils/dateUtils.ts
- src/main/routes/features/claim/yourDetails/claimantDoBController.ts
- src/test/unit/routes/features/claim/claimantDoBController.test.ts
https://tools.hmcts.net/jira/browse/CIV-13635
incorrect error message
```
[ ] Yes
[x] No
```
> CIV-13635 incorrect error message

- src/main/modules/i18n/locales/cy.json
https://tools.hmcts.net/jira/browse/CIV-13340
Update Welsh Translation
```
[ ] Yes
[x] No
```
> CIV-13340 Welsh Translation

- src/main/assets/js/language-toggle.js
- src/main/modules/i18n/locales/cy.json
https://tools.hmcts.net/jira/browse/CIV-13249
https://tools.hmcts.net/jira/browse/CIV-13372
```
[ ] Yes
[ ] No
```
> CIV-0000 Bulking branch to master

- src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
- src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
> CIV-13741 Dashboard notifications automated tests

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
https://tools.hmcts.net/jira/browse/CIV-9446
Fixed typo in Page content from siders to sides
```
[ ] Yes
[x ] No
```
> CIV-9446 Fixed typo in word siders to sides

- src/main/common/utils/externalURLs.ts
- src/main/views/external-urls.njk
https://tools.hmcts.net/jira/browse/CIV-13706
```
[ ] Yes
[x ] No
```
> CIV-13706 eligibility broken links fixed

- src/test/unit/routes/features/claim/generalApplication/requestingReasonController.test.ts
> CIV-0000 unit test fix

- README.md
- src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
- src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
- src/test/functionalTests/tests/nonprod/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
> CIV-0000 Update README.md

- src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
- src/main/common/utils/taskList/taskListBuilder.ts
- src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
- src/main/routes/features/response/taskListController.ts
- src/main/routes/guards/allResponseTasksCompletedGuard.ts
- src/main/services/features/common/taskListService.ts
- src/test/unit/common/utils/taskList/taskListBuilder.test.ts
- src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
- src/test/unit/routes/features/response/taskListController.test.ts
- check new screens for task status
```
[ ] Yes
[ ] No
```
> CIV-0000 Minti fix task status

- Jenkinsfile_CNP
> CIV-0000 Sync ithc branches for CUI

- src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
https://tools.hmcts.net/jira/browse/CIV-14121
This amends the notifications used in the FTs according to the changes done in the batch 5 fixes for the notifications formatting.
```
[ ] Yes
[X] No
```
> CIV-14121 Amending notifications on FTs according to notifications changed in batch 5

- src/main/common/models/claimantResponse/ccdClaimantResponse.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
- src/main/routes/features/claimantResponse/claimantResponseTasklistController.ts
- src/main/routes/features/claimantResponse/incompleteClaimantResponseSubmissionController.ts
- src/main/routes/guards/claimantResponseCheckYourAnswersGuard.ts
- src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
- src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/claimantHearingRequirementsSectionTasks.ts
- src/main/services/features/common/buildFastTrackHearingRequirements.ts
- src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
- src/main/services/translation/response/ccdTranslation.ts
- src/main/services/translation/response/convertToCCDDisclosureOfDocuments.ts
- src/main/services/translation/response/convertToCCDDocumentsToBeConsidered.ts
- src/test/functionalTests/specClaimHelpers/api/steps.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/defendantResponseMultiClaim.js
- src/test/functionalTests/tests/nonprod/minti_LiPvLiP_intermediate_track_tests.js
- src/test/functionalTests/tests/nonprod/minti_LiPvLiP_multi_track_tests.js
- src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
- src/test/unit/services/features/claimantResponse/claimantResponseTasklistService.test.ts
- src/test/unit/services/translation/response/convertToCCDDisclosureOfDocuments.test.ts
- src/test/unit/services/translation/response/convertToCCDDocumentsToBeConsidered.test.ts
https://tools.hmcts.net/jira/browse/CIV-13784
- CCD translation for claimant minti fields + CYA
- api test steps for minti claimant
```
[ ] Yes
[ ] No
```
https://github.com/hmcts/civil-ccd-definition/pull/4553
https://github.com/hmcts/civil-service/pull/4980
> CIV-13784 Claimant lip minti cya + CCD translation

- config/default.yaml
https://tools.hmcts.net/jira/browse/DTSCCI-5
Fix the dynatrace tag
```
[ ] Yes
[ ] No
```
> DTSCCI-005 - fix js tag

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
DTSCCI-490
remove deprecated property volume lib
```
[ ] Yes
[ ] No
```
> DTSCCI-490 remove deprecated property volume lib

- bin/pull-latest-release-asset.sh
- bin/utils/idam-lease-user-token.sh
> update docker image hmctspublic.azurecr.io/imported/

- bin/pull-latest-release-asset.sh
- bin/utils/idam-lease-user-token.sh
Reverts hmcts/civil-citizen-ui#4134
> Revert "update docker image hmctspublic.azurecr.io/imported/"

- bin/import-bpmn-diagram.sh
- bin/import-dmn-diagram.sh
- bin/import-wa-bpmn-diagram.sh
- bin/utils/ccd-add-role.sh
- bin/utils/ccd-import-definition.sh
> update docker image hmctspublic.azurecr.io/imported/toolbelt/oathtool

- Jenkinsfile_CNP
- package.json
> CIV-0000 Fixed master

- src/main/modules/helmet/index.ts
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=2662&projectKey=DTSCCI&view=detail&selectedIssue=DTSCCI-521
Try to resolve CSP issue with Dynatrace
```
[ ] Yes
[ ] No
```
> DTSCCI-005 - Add dynatrace domain to connectSrc whitelist

- config/default.yaml
https://tools.hmcts.net/jira/browse/DTSCCI-592
Switch dynatrace tag to prod version
```
[ ] Yes
[ ] No
```
> DTSCCI-592 - Update dynatrace tag to prod version

- package.json
- yarn.lock
> CIV-0000 Update: ws package

- src/main/common/form/validators/isAllowedMimeType.ts
- src/main/services/features/caseProgression/TypeOfDocumentSectionMapper.ts
> CIV-0000  testpr for rtf file

- src/test/functionalTests/commonFeatures/home/steps/login.js
> DTSCCI-796 - Removing 10 second waits

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
https://tools.hmcts.net/jira/browse/CIV-13605
Apply help with fees page not replacing the placeholders
&&
has anything changed page title
```
[ ] Yes
[x] No
```
> CIV-13605 replacing the placeholders

- src/main/modules/helmet/index.ts
> CIV-0000 changes doubleclick to wildcard, added GTM main url to CSP policies

- src/main/modules/i18n/locales/cy.json
PR for https://tools.hmcts.net/jira/browse/CIV-15381
> CIV-15381 Remove Quote Mark - Welsh Amends

- src/main/common/utils/interestUtils.ts
- src/test/unit/common/utils/interestUtils.test.ts
NA
fixed unit test
```
[ ] Yes
[x] No
```
> CIV-0000 - fixed unit tests.

- src/main/modules/utilityService.ts
- src/main/routes/features/claim/createDraftClaim.ts
- src/main/routes/features/dashboard/claimantDashboardController.ts
- src/test/unit/routes/features/claim/createClaimDraft.test.ts
https://tools.hmcts.net/jira/browse/CIV-15493
Fix dashboard for draft case by redoing check on whether claimId equals draft
```
[ ] Yes
[x] No
```
> CIV-15493 -  Fix for draft claim dashboard

- src/main/routes/features/claim/interest/claimTotalInterestController.ts
- src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
- src/test/unit/routes/features/claim/iterest/claimTotalInterestController.test.ts
https://tools.hmcts.net/jira/browse/CIV-15490
CUI 'Breakdown interest' option redirecting to HWf
```
[ ] Yes
[x] No
```
> CIV-15490 Breakdown interest option

- charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
- src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllClaimantResponse.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllFastTrackDefendantResponse.js
- src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllSmallClaimsDefendantResponse.js
- src/test/functionalTests/tests/nonprod/minti_LiPvLiP_intermediate_track_tests.js
- src/test/functionalTests/tests/nonprod/minti_LiPvLiP_multi_track_tests.js
- src/test/functionalTests/tests/nonprod/mt_it_LiPvLiP_tests.js
> CIV-000 remove field defenceAdmitPartPaymentTimeRouteRequired from reject all payloads 

- src/main/views/claim-details-tpl-dashboard.njk
- src/main/views/claim-details-tpl.njk
https://tools.hmcts.net/jira/browse/CIV-15545
Testing support incorrectly displayed in production
```
[ ] Yes
[x] No
```
> CIV-15545 testing support for prod

- src/main/common/form/validators/emailValidator.ts
- src/main/services/features/claim/submission/submitClaim.ts
- src/main/services/translation/response/convertToCCDParty.ts
- src/test/e2eTests/response/steps/response.js
- src/test/unit/routes/features/claim/defendantEmailController.test.ts
> CIV-0000 fix for e2e test

- src/main/common/form/validators/emailValidator.ts
- src/test/unit/routes/features/claim/defendantEmailController.test.ts
https://tools.hmcts.net/jira/browse/CIV-15569
Change email check to >320 chars
```
[ ] Yes
[x] No
```
> CIV-15569 Change email check to >320 chars

- src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
https://tools.hmcts.net/jira/browse/CIV-15573
```
[ ] Yes
[ ] No
```
> CIV-15573 logs added to analyse the payment failure issues

- src/main/modules/draft-store/index.ts
> CIV-0000 remove log statement

- src/main/modules/error/index.ts
> CIV-0000 added code for handling 401 errors 

- src/main/app.ts
- src/main/modules/oidc/index.ts
- src/test/unit/modules/oidc/index.test.ts
https://tools.hmcts.net/jira/browse/CIV-15599
Payment gateway return url get call is ignored when user session expires
```
[ ] Yes
[ ] No
```
> CIV-15599 - Payment gateway return url get call is ignored when user session expires

- src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
- src/main/services/dashboard/dashboardInterpolationService.ts
https://tools.hmcts.net/jira/browse/CIV-15448
```
[ ] Yes
[ ] No
```
> CIV-15448 CoSC - Add guidelines link

- sonar-project.properties
- src/main/assets/js/disable-submit.js
- src/main/index.js
- src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
- src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
- src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
- src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
https://tools.hmcts.net/jira/browse/CIV-15666
disable submit button
```
[ ] Yes
[x] No
```
> CIV-15666 disable submit button

- src/main/views/features/caseProgression/check-answers.njk
PR for https://tools.hmcts.net/jira/browse/CIV-15350
> CIV-15350 Accessibility Issue - Adding Header Only If Title Is Available

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- src/main/modules/nunjucks/index.ts
- src/main/views/claim-details-tpl-dashboard.njk
- src/main/views/claim-details-tpl.njk
Reverts hmcts/civil-citizen-ui#4747
> Revert "CIV-15545 flag testing support enabled"

- src/test/functionalTests/tests/nonprod/cp_LiPvLiP_request_for_reconsideration_tests.js
PR for https://tools.hmcts.net/jira/browse/CIV-15647
> CIV-15647 Skipping the FRF FTs 

- src/main/common/models/generalApplication/applicationResponse.ts
- src/main/routes/features/generalApplication/response/viewApplicationController.ts
- src/main/services/features/generalApplication/generalApplicationService.ts
- src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
- src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
https://tools.hmcts.net/jira/browse/CIV-15773
Show same view as applicant after response
```
[ ] Yes
[x] No
```
> CIV-15773 Show same view as applicant after response

- src/main/common/models/generalApplication/applicationResponse.ts
- src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
https://tools.hmcts.net/jira/browse/CIV-15802
```
[ ] Yes
[ ] No
```
> CIV-15802 Update General AppRespondent list

- src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
- src/main/services/features/generalApplication/checkAnswers/checkAnswersService.ts
- src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
https://tools.hmcts.net/jira/browse/CIV-15794
N245 at Ga CYA
```
[ ] Yes
[x] No
```
> CIV-15794 N245 at Ga CYA

- src/main/modules/i18n/locales/en.json
- src/test/functionalTests/citizenFeatures/GA/pages/agreementFromOtherParty.js
- src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-agreement-from-other-party.html
https://tools.hmcts.net/jira/browse/CIV-15807
ga agreement from other parties
```
[ ] Yes
[x] No
```
> CIV-15807 agreement from other parties

- src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
- src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/courtLocation.js
- src/test/functionalTests/codecept.conf.js
> CIV-0000 fixed functional tests

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/dashboard/claim-summary-redesign.njk
- src/main/views/features/dashboard/dashboard.njk
- src/main/views/macro/banner.njk
PR for https://tools.hmcts.net/jira/browse/CIV-15967
> CIV-15967 CUI Banner Implementation For CUI_CP Release

- src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/viewYourOptionsBeforeDeadline/viewYourOptionsBeforeDeadline.js
> DTSCCI-000 fix date methods in error tests

- src/main/common/models/generalApplication/uploadN245GAFiles.ts
- src/main/routes/features/generalApplication/uploadN245FormController.ts
https://tools.hmcts.net/jira/browse/CIV-15931
N245 upload a file is mandatory
```
[ ] Yes
[x] No
```
> CIV-15931 upload a file is mandatory

- src/main/services/features/generalApplication/generalApplicationService.ts
- src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
https://tools.hmcts.net/jira/browse/CIV-15955
```
[ ] Yes
[x] No
```
> CIV-15955 Remove unnecessary data based on the type of application.

- src/main/services/features/generalApplication/generalApplicationService.ts
- src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
https://tools.hmcts.net/jira/browse/CIV-16013
only app can view request more info 
```
[ ] Yes
[x] No
```
> CIV-16013 only app can view

- src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
- src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
https://tools.hmcts.net/jira/browse/CIV-16247
Display correct payment reference
```
[ ] Yes
[x] No
```
> CIV-16247 Display correct payment reference

- src/test/e2eTests/tests/generalApplication/LipvsLipStrikeOut.js
> DTSCCI-00000 remove failing test for now as PRs are blocked

- src/main/modules/i18n/locales/cy.json
https://tools.hmcts.net/jira/browse/CIV-16228
```
[ ] Yes
[X] No
```
> CIV-16228 fixed Welsh translation

- src/main/services/features/generalApplication/generalApplicationService.ts
- src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
https://tools.hmcts.net/jira/browse/CIV-16285
removed redundant question
```
[ ] Yes
[x] No
```
> CIV-16285 removed redundant question

- src/main/views/features/generalApplication/additionalDocuments/submitted.njk
https://tools.hmcts.net/jira/browse/CIV-16264
add Contact us section to upload additional document confirmation page
```
[ ] Yes
[x] No
```
> CIV-16264 contact us

- src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationHearingDetails.ts
- src/main/common/models/generalApplication/hearingArrangement.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
- src/main/services/translation/generalApplication/ccdTranslation.ts
- src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationRows.test.ts
- src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
- wiremock/mappings/civil-service-mapping.json
https://tools.hmcts.net/jira/browse/CIV-16223
```
[ ] Yes
[x] No
```
> CIV-16223 add Without a hearing option

- src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
- src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
https://tools.hmcts.net/jira/browse/CIV-15855
https://tools.hmcts.net/jira/browse/CIV-16222
remove evidence section from ga summary
```
[ ] Yes
[x] No
```
> CIV-15855 CIV-16222 remove evidence section from ga summary

- src/main/common/form/models/defence.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
DTSCCI-1369
defence summary char limit changed 400 to 800
```
[ ] Yes
[ ] No
```
> DTSCCI-1369 defence summary char limit changed 400 to 800

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.aat.template.yaml
- charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
- charts/civil-citizen-ui/values.yaml
> DTSCCI-1364 upgrade ccd chart

- charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
- src/main/services/features/generalApplication/additionalDocumentService.ts
- src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
- src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
> CIV-00000  Update enable Notify email

- src/main/views/macro/generalApplication/application-summary.njk
https://tools.hmcts.net/jira/browse/CIV-16251
fixed link colour
```
[ ] Yes
[x ] No
```
> CIV-16251 - GA - Fix colour of the link 'View application'

- src/main/common/utils/externalURLs.ts
- src/main/views/external-urls.njk
- src/test/utils/mocks/a11y/mock-first-contact-start.html
> CIV-00000 Update ccbc url to CNBC

- Jenkinsfile_CNP
> CIV-00000 UPdate Jenkins file to point ccd and gaccd to the master branches

- src/main/views/macro/banner.njk
Remove banner erroneously showing in prod
```
[ ] Yes
[x] No
```
> CIV-0000 Remove banner

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/claim/interest/claimant-interest-from.njk
- src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
- src/test/utils/mocks/a11y/mock-claim-interest-date.html
https://tools.hmcts.net/jira/browse/DTSCCI-1494
```
[ ] Yes
[X] No
```
> DTSCCI-1494 Amend the interest from page

- charts/civil-citizen-ui/values.enableWA.preview.template.yaml
NA
Preview build issue.
```
[ ] Yes
[x] No
```
> CIV-0000 - Update values.enableWA.preview.template.yaml

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/views/features/claim/interest/interest-type.njk
https://tools.hmcts.net/jira/browse/DTSCCI-1499
```
[ ] Yes
[ ] No
```
> DTSCCI-1499 Amend the How do you want to claim interest page

- src/main/common/form/models/claimantResponse/chooseHowToProceed.ts
- src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayByInstallments_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayBySetDate_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayByInstallments_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayBySetDate_claimantResponse.js
- src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
https://tools.hmcts.net/jira/browse/DTSCCI-1695
```
[ ] Yes
[X] No
```
> DTSCCI-1695 implement validation to stop users from selecting settlement agreement

- src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayByInstallments_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayBySetDate_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayByInstallments_claimantResponse.js
- src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayBySetDate_claimantResponse.js
- src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
- src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
- src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
- src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
https://tools.hmcts.net/jira/browse/DTSCCI-1695
```
[ ] Yes
[X] No
```
> DTSCCI-1695 skip tests which select sign a settlement agreement as its temporarily unavailable

- src/test/functionalTests/citizenFeatures/common/govPay.js
- src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
> DTSCCI-1781 test redoing the pr for the purpose of getting the fix in

- package.json
- src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
> CIV-1781 test 1

- src/main/modules/health/index.ts
removed log
NA
Removed log
```
[ ] Yes
[x] No
```
> CIV-0000 - Update index.ts

- charts/civil-citizen-ui/Chart.yaml
- charts/civil-citizen-ui/values.preview.template.yaml
> DTSCCI-1892 reduce em log

- src/test/functionalTests/tests/common/LRvLiP_case_offline_tests.js
- src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_admitAll_dateToPayOn_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_admitAll_repaymentPlan_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_AlreadyPaid_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_dateToPayOn_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_fastTrack_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_repaymentPlan_tests.js
- src/test/functionalTests/tests/prod/LRvLip_response_rejectAll_AlreadyPaid_tests.js
- src/test/functionalTests/tests/prod/carm_LiPvLiP_company_small_claims_tests.js
> DTSCCI-1868 2 Add Case-Offline Tag and Turn Off Carm and LRvLIP Tests in Prod

- src/main/common/utils/dateUtils.ts
- src/main/common/utils/interestUtils.ts
- src/test/unit/common/utils/dateUtils.test.ts
> DTSCCI-1799 remove after 4pm and additional days in calculation

- src/main/app/auth/launchdarkly/launchDarklyClient.ts
- src/main/routes/features/dashboard/viewDefendantInformationController.ts
- src/test/unit/routes/features/dashboard/viewDefendantInformationController.test.ts
https://tools.hmcts.net/jira/browse/CIV-17082
Implemented changes to correctly display LR defendant details only when the NOC feature toggle is enabled.
```
[ ] Yes
[x] No
```
> CIV-17082 - CUI Pods in production are restarting frequently and on regular basis

- src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/welshLanguage.js
> CIV-0000 - Fixed FT

- src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
DTSCCI-2069
eligibility guidance hwf
```
[ ] Yes
[ ] No
```
> DTSCCI-2069 eligibility guidance hwf

- package.json
- yarn.lock
> CIV-0000 - Update package.json

- src/main/services/dashboard/dashboardService.ts
- src/test/unit/services/features/caseProgression/dashboardService.test.ts
https://tools.hmcts.net/jira/browse/CIV-17223
```
[ ] Yes
[x] No
```
> CIV-17223 - add the link of Contact the court' link not available under 'Applications'

- src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayImmediately_tests.js
- src/test/functionalTests/tests/prod/minti_LiPvLiP_tests.js
> DTSCCI-2168: Skip failing tests

- src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/confirmation.js
- src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
- src/test/functionalTests/tests/common/LRvLip_response_partAdmit_HaventPaid_immediatePay_tests.js
- src/test/functionalTests/tests/prod/carm_LiPvLiP_Individual_small_claims_tests.js
> More test fixes

- jest.config.js
- package.json
https://tools.hmcts.net/jira/browse/DTSCCI-1746
```
[ ] Yes
[X] No
```
> DTSCCI-1746 increase unit test workers

- src/main/views/features/queryManagement/qm-confirmation-template.njk
https://tools.hmcts.net/jira/browse/CIV-17660
```
[ ] Yes
[ ] No
```
> CIV-17660 fix accessibility

- src/main/common/models/generalApplication/applicationResponse.ts
- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- src/main/routes/features/generalApplication/response/viewApplicationController.ts
- src/main/views/features/generalApplication/response/view-application.njk
https://tools.hmcts.net/jira/browse/CIV-17603
Added additional content on application details screen
```
[ ] Yes
[x ] No
```
> CIV-17603 Added additional content on application details screen

- .github/renovate.json
> DTSCCI-0000  renovate.json

- src/main/modules/i18n/locales/cy.json
- src/main/modules/i18n/locales/en.json
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-17724
Corrected banner message when documents are in translation
```
[ ] Yes
[x ] No
```
> CIV-17724 Update CUI 'Welsh' banner wording

- charts/civil-citizen-ui/values.preview.template.yaml
- src/test/functionalTests/tests/mainClaimWelsh/LipVsLip_claimant_as_welsh.js
- src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation__defendant_English_document_welsh_tests.js
> DTSCCI-2369 fix for defendant response fully admits pay immediately notification not showing amount.

- .github/renovate.json
- Jenkinsfile_CNP
- README.md
> DTSCCI-0000 Removing fullDeploy label requirement
